import 'jquery'
import 'angular'
import 'angular-animate'
import 'angular-resource'
import 'angular-route'

import 'bootstrap/dist/css/bootstrap.css'
import './app.css'
import './app.animations.css'

import './app.module'
import './core/core.module'
import './core/checkmark/checkmark.filter'
import './core/phone/phone.module'
import './core/phone/phone.service'
import './phone-list/phone-list.module'
import './phone-list/phone-list.component'
import './phone-detail/phone-detail.module'
import './phone-detail/phone-detail.component'
import './app.animations'
import './app.config'